list_of_events: Document fs_dictmap_dict_write_uncertain event
dovecot/documentation pull request #142
Opened 2020-10-08 12:32 UTC by cmouse

JIRA: DOV-4119

2020-10-08 14:56 UTC, sirainen requested changes

2020-10-08 14:56 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> ++-----------------------+------------------------------------------------------+
Why two lines? Normally there's just one.

2020-10-08 14:56 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +| cleanup               | success, failed or disabled                          |
Should have a longer explanation, like: If the uncertain write was attempted to be cleaned (deleted), result of the attempt.

2020-10-08 14:56 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +The event is sent whenever a dict write is uncertain.
Could explain a bit more, like: For example writes to Cassandra may eventually succeed even if the write initially appeared to fail.

2020-10-08 14:57 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +| cleanup               | success, failed or disabled                          |
Maybe also point to the setting that can be used to enable/disable it?

2020-10-19 10:37 UTC, sirainen requested changes

2020-10-19 10:37 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +| cleanup               | success, failed or disabled. Indicates if uncertain   |
Using \`\` quoting could make these choices clearer. Looks like they're missing from other places too .. but that could be fixed separately.

2020-10-21 08:11 UTC, sirainen approved these changes

2020-11-11 15:52 UTC, thuovila approved these changes

2020-11-23 07:16 UTC, merged