list_of_events: Add fs_dictmap_empty_bucket_iterated event
dovecot/documentation pull request #156
Opened 2020-12-08 09:35 UTC by vmo69

DOV-3954

2020-12-08 10:09 UTC, sirainen requested changes

2020-12-08 10:09 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +        In addition ``max_bucket`` can be shrinked in case a iteration discovers empty
* can be shrunk
 * an iteration

2020-12-08 10:51 UTC, vmo69 commented on source/admin_manual/list_of_events.rst
> +        In addition ``max_bucket`` can be shrinked in case a iteration discovers empty
fixed.

2020-12-10 14:43 UTC, sirainen commented on source/configuration_manual/mail_location/obox/dictmap_cassandra_objectid.rst
> +    value_type = uint,string # for v2.3.14 and newer
writetime should also be uint

2020-12-14 12:35 UTC, sirainen approved these changes

2020-12-17 10:49 UTC, merged