mail_location/index: Clarify BROKENCHAR a bit more
dovecot/documentation pull request #177
Opened 2021-01-21 12:03 UTC by sirainen

2021-01-21 13:19 UTC, thuovila requested changes
Should we add  .. versionchanged:: to mark when the behavior was extended?

2021-01-21 13:43 UTC, sirainen commented
I suppose the only change really is that conflicting hierarchy separators are now escaped. Added. Otherwise there were also some fixes, but maybe that's not worth mentioning since it would be pretty ambiguous anyway ("and various fixes").

2021-01-25 06:47 UTC, cmouse approved these changes

2021-01-25 07:12 UTC, thuovila approved these changes

2021-01-25 07:14 UTC, merged