admin_manual: Add fts_dovecot_too_many_triplets event to the list of …
dovecot/documentation pull request #195
Opened 2021-03-05 14:34 UTC by Sergey-Kitov

…events

2021-03-05 16:02 UTC, sirainen requested changes

2021-03-05 16:02 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> ++===============+==================================================+
| Inherits from :ref:\`event_mail_user\`                                           |

2021-03-09 08:43 UTC, Sergey-Kitov commented on source/admin_manual/list_of_events.rst
> +Event emitted when number of triplets exceeds the limit defined by fts_dovecot_max_triplets setting
The setting is added, but recommended value is unclear for me, it either should be selected or removed from the description.

2021-03-11 22:32 UTC, sirainen approved these changes

2021-03-18 16:10 UTC, merged