settings: Document changes to ssl_min_protocol
dovecot/documentation pull request #213
Opened 2021-04-01 14:20 UTC by cmouse

JIRA: DOV-4306

2021-04-01 15:16 UTC, sirainen requested changes

2021-04-01 15:16 UTC, sirainen commented on source/settings/core.rst
> + * ``LATEST`` - Support latest version available.
Support only the latest version available.

2021-04-01 15:16 UTC, sirainen commented on source/settings/core.rst
> + * ``TLsv1.3`` - Support TLSv1.3+.
Also s/TLs/TLS/

2021-04-07 10:48 UTC, vmo69 approved these changes

2021-04-08 07:23 UTC, sirainen requested changes

2021-04-08 07:23 UTC, sirainen commented on source/settings/core.rst
> + * ``LATEST`` - Support only latest version available.
"the latest"

2021-04-13 08:48 UTC, merged