settings/core: Document ssl_cipher_suites
dovecot/documentation pull request #231
Opened 2021-05-03 14:50 UTC by cmouse

JIRA: DOV-4306

2021-05-03 15:26 UTC, sirainen requested changes

2021-05-03 15:26 UTC, sirainen commented on source/settings/core.rst
> +The list of SSL cipher suites to use, in order of preference.
Could have some kind of example values. and/or link to OpenSSL documentation about it.

2021-05-03 15:26 UTC, sirainen commented on source/settings/core.rst
> +.. versionadded:: v2.3.15
versionadded should be before "default" like it is elsewhere

2021-05-03 16:44 UTC, sirainen commented
/github/workspace/source/settings/core.rst:4305: WARNING: Unknown target name: "https://wiki.openssl.org/index.php/tls1.3#ciphersuites".

2021-05-03 17:06 UTC, cmouse commented
need to check syntax...

2021-05-04 08:11 UTC, sirainen approved these changes

2021-05-05 13:18 UTC, merged