admin_mainual: lua: Document environment change in 2.3.17
dovecot/documentation pull request #286
Opened 2021-09-06 10:29 UTC by siavasht

Global variables are disallowed.

2021-09-07 08:47 UTC, cmouse requested changes

2021-09-07 08:47 UTC, cmouse commented on source/admin_manual/lua.rst
> +.. versionchanged:: 2.3.17 Scripts are run in a confined environment in which
`Scripts run in a`

2021-09-07 08:54 UTC, cmouse commented
Commit says `admin_mainual`

2021-09-07 15:28 UTC, siavasht commented on source/admin_manual/lua.rst
> +.. versionchanged:: 2.3.17 Scripts are run in a confined environment in which
fixed

2021-09-09 11:25 UTC, sirainen approved these changes

2021-09-15 07:56 UTC, cmouse commented
Need to document the new `dovecot.restrict_globals()` function too.

2021-09-15 11:59 UTC, siavasht commented
Updated with new function name.

2021-09-15 12:08 UTC, sirainen requested changes

2021-09-15 12:08 UTC, sirainen commented on source/admin_manual/lua.rst
> +   If a script needs to define a variable, they must declar them as local i.e.
declare

2021-09-15 12:08 UTC, sirainen commented on source/admin_manual/lua.rst
> +   `dovecot.restrict_global_variables(false)`.
probably needs double-\`\`?

2021-09-15 12:19 UTC, siavasht commented on source/admin_manual/lua.rst
> +   `dovecot.restrict_global_variables(false)`.
Yeah, fixed.

2021-09-15 12:32 UTC, sirainen approved these changes

2021-09-17 08:33 UTC, cmouse approved these changes

2021-09-17 08:34 UTC, merged