maildir: Document conflicting dovecot.list.index behavior
dovecot/documentation pull request #328
Opened 2021-10-26 20:59 UTC by slusarz

DOP-2191

2021-10-27 06:14 UTC, sirainen submitted a review, later dismissed

2021-11-03 07:59 UTC, vmo69 requested changes

2021-11-03 07:59 UTC, vmo69 commented on source/configuration_manual/mail_location/Maildir/index.rst
> +For example::
This(`::`) is nice and compact compared to ``.. code-block::none`` but it defaults to highlight the code as python which makes colons and brackets weirdly big when this is getting rendered.

2021-11-03 07:59 UTC, vmo69 commented on source/configuration_manual/mail_location/Maildir/index.rst
> +the above example, this is done by changing the "Alias location" line to::
Same issue here `::` vs `.. code-block::none`

2021-11-05 08:18 UTC, vmo69 approved these changes

2021-11-08 08:50 UTC, cmouse approved these changes

2021-11-08 08:51 UTC, merged