Imapc pop3c improvements
dovecot/documentation pull request #342
Opened 2021-11-10 20:09 UTC by slusarz

2021-11-10 20:51 UTC, sirainen requested changes

2021-11-10 20:51 UTC, sirainen commented on source/admin_manual/mailbox_formats/pop3c.rst
> +optionally a more capable storage.
I see this is just copied from imapc, but I don't see how pop3c could be treated as anything else than a dummy storage. :) So just remove this sentence?

Also could say that the the POP3 mailbox is visible as the INBOX folder on Dovecot side.

2021-11-10 20:51 UTC, sirainen commented on source/configuration_manual/mail_location/pop3c/index.rst
> +See also :ref:`setting-pop3c_user`.
were we supposed to start using `.. seealso::`?

2021-11-10 20:51 UTC, sirainen commented on source/configuration_manual/mail_location/pop3c/index.rst
> +- Values: <empty>, ``no``, ``pop3s``, ``starttls``
Where are you getting empty from? The default is "no", and empty value is invalid:

```
Invalid -o parameter pop3c_ssl=: Invalid value:
```

2021-11-10 20:51 UTC, sirainen commented on source/configuration_manual/mail_location/pop3c/index.rst
> +server.
IMAP has LOGIN, but pop3 has USER+PASS. So this should say something else than LOGIN. Same elsewhere in this page.

2021-11-11 19:55 UTC, slusarz commented
Let's hold off on this until #344 is resolved.  I explicitly did not change any of the pop3c settings generation there, since this MR is pending (and will need to be refactored when/if #344 is approved).

2021-12-20 04:30 UTC, slusarz commented
I've implemented all the suggestions.  However ... these changes should be done as part of the general settings conversion that is happening in #344.  The imapc changes is just part of the conversion anyway.  The pop3c changes are a bit more substantial, but doesn't make any sense to keep the old settings and then deal with merge issues, so I've moved pop3c conversion to a separate commit in #344.  Closing this MR.

2021-12-20 04:30 UTC, closed without merging