developer_manual/design: Update mail* pages
dovecot/documentation pull request #361
Opened 2021-12-10 02:59 UTC by sirainen

2021-12-10 07:01 UTC, cmouse requested changes

2021-12-10 07:01 UTC, cmouse commented on source/developer_manual/design/mailbox_list.rst
> +-  ``mode``: Creation mode, like 0600.
definition list here too maybe?

2021-12-10 07:01 UTC, cmouse commented on source/developer_manual/design/mailbox_list.rst
>        -  Example: "foo/bar" exists, but "foo" doesn't. "%", "foo" or
It is better to use `` for escaping.

2021-12-10 07:01 UTC, cmouse commented on source/developer_manual/design/mailbox_transaction.rst
> +-  ``MAILBOX_TRANSACTION_FLAG_NO_CACHE_DEC``: Don't update caching decisions
definition list

2021-12-17 10:29 UTC, sirainen commented
Added definition lists.

2021-12-17 11:12 UTC, cmouse approved these changes

2021-12-17 13:14 UTC, merged