Spell check
dovecot/documentation pull request #371
Opened 2021-12-28 13:13 UTC by jsoref

This adds [check-spelling](https://check-spelling.dev/)`@v0.0.20-alpha3` using [check-spelling/spell-check-this@prerelease](https://github.com/check-spelling/spell-check-this/tree/prerelease/.github).

I'm not including experimental update. We're using it internally, but I think it's still a bit too rough.

You'll want to review the expect file as it's essentially the current baseline. Note this PR includes one extra typo fix for an item that snuck in between when I started #365 and when it was merged.

Any open PRs should be poked (force-push rebase is probably the best approach, although adding a null commit would also work) or else you risk them adding typos and confusing people.

I'm generally quite available if you need help (I respond to `@`, and I'm reachable on irc, or by email).

2021-12-28 13:20 UTC, cmouse approved these changes

2021-12-28 13:32 UTC, cmouse requested changes

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +Besidesm
fixable typo

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +Besidesm
`Besidesm if the system was just` => `Besides if the system was just`

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +bruteforce
`bruteforce` => `brute force`

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +Uset
This is also typo, it should be User.

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +uzing
This is a typo, it should be `using`

2021-12-28 13:32 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +virtualisation
not sure if this should be virtualization.

2021-12-28 15:22 UTC, cmouse commented
Please remove the open discussions from expect.txt, and close them.

2021-12-28 15:35 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +LTMP
this should be LMTP

2021-12-28 15:38 UTC, cmouse commented on .github/actions/spelling/expect.txt
> +ntml
should be ntlm

2021-12-28 16:07 UTC, sirainen requested changes

2021-12-28 16:10 UTC, jsoref commented on .github/actions/spelling/expect.txt
> +antispam
The former redirects from:
https://oxpedia.org/wiki/index.php?title=AppSuite:Dovecot_Antiabuse_Shield =>
https://oxpedia.org/wiki/index.php?title=AppSuite:OX_Abuse_Shield

2021-12-28 16:11 UTC, jsoref commented on .github/actions/spelling/expect.txt
> +antispam
The latter is doable, but it's a non-trivial change (involving renaming a file):
```
source/configuration_manual/howto/antispam_with_sieve.rst:.. _howto-antispam_with_imapsieve:
source/configuration_manual/howto/antispam_with_sieve.rst:Replacing antispam plugin with IMAPSieve
source/configuration_manual/howto/antispam_with_sieve.rst:https:/ /
source/configuration_manual/sieve/plugins/imapsieve.rst:See :ref:`Replacing antispam plugin with
source/configuration_manual/sieve/plugins/imapsieve.rst:IMAPSieve <howto-antispam_with_imapsieve>`
source/configuration_manual/spam_reporting.rst:.. seealso:: :ref:`howto-antispam_with_imapsieve`
```

You can also make changes such as this after this merges.

(I'll do the former now.)

2021-12-30 07:18 UTC, cmouse submitted a review, later dismissed

2021-12-30 07:20 UTC, jsoref commented
Checks for the latest merge failed: https://github.com/jsoref/dovecot-documentation/commit/6b7ddeb9b5badf2da58f2266ee151f2dcbfa1789#commitcomment-62676671

2021-12-30 07:20 UTC, cmouse commented
Looks like it still complains about ECDHE.?

2021-12-30 07:34 UTC, sirainen approved these changes

2021-12-30 07:35 UTC, merged