configuration_manual/fts/tokenization: Better wording for base64 filter description
dovecot/documentation pull request #386
Opened 2022-01-13 11:01 UTC by mbettini-ox

2022-01-13 11:16 UTC, cmouse commented on source/configuration_manual/fts/tokenization.rst
> +
e.g. any (even single) 50-character runs in base64 set are recognized as base64 and ignored in indexing.

2022-01-13 11:16 UTC, cmouse commented on source/configuration_manual/fts/tokenization.rst
> +Given the rules above, the indexed extra content (due to sequences split across chunks)
convert () to ,

2022-01-14 10:17 UTC, sirainen requested changes

2022-01-14 10:17 UTC, sirainen commented on source/configuration_manual/fts/tokenization.rst
> +does not impact significantly the quality of the filter.
This is a bit difficult to read and not entirely clear what it means. Maybe:

If the base64 sequences happen to be split across different chunks, they might not be detected as base64. In this case the base64 content is still indexed. However, this happens rarely enough that it does not significantly impact the quality of the filter.

2022-01-14 10:29 UTC, sirainen approved these changes

2022-01-14 10:29 UTC, merged