Remove login_access_sockets
dovecot/documentation pull request #428
Opened 2022-03-25 07:39 UTC by cmouse

JIRA: DOV-5016

2022-03-25 07:43 UTC, sirainen submitted a review, later dismissed

2022-03-25 07:43 UTC, sirainen commented
Hm. Upgrading page update also?

2022-03-25 08:19 UTC, cmouse commented
Merge #423 first

2022-03-30 13:22 UTC, sirainen commented
https://github.com/dovecot/documentation/pull/423 is merged, but still no mention in upgrading page.

2022-03-30 13:22 UTC, sirainen commented
https://github.com/dovecot/documentation/pull/423 is merged, but still no mention in upgrading page.

2022-03-31 06:41 UTC, cmouse commented
Merge #437 first.

2022-03-31 06:48 UTC, sirainen requested changes

2022-03-31 06:48 UTC, sirainen commented on source/installation_guide/upgrading/from-2.3-to-3.0.rst
> +| ``login_access_sockets``                                   | Dovecot will fail to start if this setting is present in configuration.                  |
```
``login_access_sockets`` setting 
```
?..

2022-03-31 07:06 UTC, sirainen approved these changes

2022-03-31 07:07 UTC, merged