admin_manual: Add fs_object_write_uncertain to list of events.
dovecot/documentation pull request #473
Opened 2022-06-02 12:15 UTC by Sergey-Kitov

2022-06-02 12:18 UTC, cmouse approved these changes

2022-06-03 08:08 UTC, sirainen requested changes

2022-06-07 07:58 UTC, sirainen requested changes

2022-06-07 07:58 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +See also :ref:`fs_dictmap_dict_write_uncertain`.
Also a similar reverse link from fs_dictmap_dict_write_uncertain -> fs_object_write_uncertain.

2022-06-07 07:58 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +.. versionadded:: 3.0.0
This should also mention v2.4. Commonly this is written v2.4.0;v3.0.0

2022-06-07 08:09 UTC, sirainen approved these changes

2022-06-08 14:40 UTC, sirainen requested changes

2022-06-08 14:40 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +When HTTP write operation times out actual outcome is uncertain.
@Sergey-Kitov could you change one more thing: "When HTTP write operation" -> "When a write HTTP operation" to make it clearer it's not a "HTTP WRITE" operation. Plus missing article.

2022-06-09 07:37 UTC, sirainen approved these changes

2022-06-09 07:39 UTC, merged