global: Update for auth_debug now being obsolete
dovecot/documentation pull request #509
Opened 2022-06-30 15:34 UTC by mbettini-ox

2022-07-02 07:32 UTC, sirainen requested changes

2022-07-02 07:32 UTC, sirainen commented on source/admin_manual/logging.rst
> +* :dovecot_core:ref:`log_debug = category=auth <log_debug>` enables all authentication debug logging (also enables :dovecot_core:ref:`auth_verbose`). Passwords are logged as `<hidden>`.
I wonder if this is true anymore. We should check and add CI test maybe.

2022-07-05 07:41 UTC, sirainen commented on source/admin_manual/logging.rst
> +* :dovecot_core:ref:`log_debug = category=auth <log_debug>` enables all authentication debug logging (also enables :dovecot_core:ref:`auth_verbose`). Passwords are logged as `<hidden>`.
I get e.g.: Jul 05 10:40:54.396001 auth: Info: passdb(tss,127.0.0.1,<fkny+AnjJNx/AAAB>): Password mismatch

2022-07-07 14:54 UTC, sirainen requested changes

2022-07-07 14:54 UTC, sirainen commented on source/admin_manual/logging.rst
> +* :dovecot_core:ref:`auth_debug_passwords=yes <auth_debug_passwords>`  removes password hiding (but only if you are not using PAM, since PAM errors aren't written to Dovecot's own logs).
extra space left before "removes"

2022-07-07 14:54 UTC, sirainen commented on source/settings/core.rst
> +   Passwords are logged as ``<hidden>``.
You can leave the "(also enables auth_verbose)" since it seems to be true still.

2022-07-07 14:54 UTC, sirainen commented on source/admin_manual/debugging/debugging_authentication.rst
>  ========================
Commit message: s/opsolete/obsolete/

2022-07-07 18:08 UTC, sirainen approved these changes

2022-07-18 11:17 UTC, cmouse commented on source/admin_manual/debugging/debugging_authentication.rst
> +Most importantly set ``log_debug = category=auth``, which makes Dovecot log a debug line for just about anything related to authentication. If you're having problems with passwords, you can also set
```
:dovecot_core:ref:`log_debug = category=auth <log_debug>`
```

2022-07-18 11:17 UTC, cmouse commented on source/admin_manual/debugging/debugging_authentication.rst
> +Most importantly set ``log_debug = category=auth``, which makes Dovecot log a debug line for just about anything related to authentication. If you're having problems with passwords, you can also set
```
:dovecot_core:ref:`auth_debug_passwords=yes <auth_debug_passwords>`
```

2022-07-18 11:17 UTC, cmouse commented on source/settings/core.rst
> +   .. note:: You also need to enable ``log_debug = category=auth``
move the `see` thing to here.

2022-07-22 08:16 UTC, cmouse approved these changes

2022-07-22 08:19 UTC, merged