fscache: Mention that ZFS does not work
dovecot/documentation pull request #577
Opened 2022-10-18 10:03 UTC by cmouse

2022-10-18 20:58 UTC, sirainen requested changes

2022-10-18 20:58 UTC, sirainen commented on source/configuration_manual/mail_location/obox/fscache.rst
> +ZFS support has been currently explicitly disabled.
It's clearer to put these into one line:

.. versionchanged:: v2.3.20 ZFS support has been currently explicitly disabled.

2022-10-19 06:01 UTC, cmouse commented
Needs https://github.com/dovecot/documentation/pull/578

2022-10-19 22:57 UTC, sirainen approved these changes

2022-10-19 22:58 UTC, merged