configuration_manual: http_storages: Remove deprecated options
dovecot/documentation pull request #595
Opened 2022-11-07 09:40 UTC by vmo69

DOV-5612

2022-11-14 22:01 UTC, sirainen approved these changes

2022-11-14 22:03 UTC, sirainen requested changes
Upgrading page should mention these also.

2022-11-16 11:37 UTC, sirainen requested changes

2022-11-16 11:37 UTC, sirainen commented on source/installation_guide/upgrading/from-2.3-to-3.0.rst
> +|                                                            | instead.                                                                                 |
`parameter. Use` here and elsewhere.

2022-11-16 12:58 UTC, cmouse approved these changes

2022-11-16 12:58 UTC, merged