Housekeeping for 2.3
dovecot/documentation pull request #616
Opened 2022-11-24 09:46 UTC by cmouse

2022-11-24 09:47 UTC, cmouse commented
Companion for #614

2022-11-24 16:49 UTC, fleischie requested changes

2022-11-24 16:49 UTC, fleischie commented on source/settings/plugin/zlib-plugin.rst
>     Name     Library (algorithm)                                Dovecot Support
The `Dovecot Support` is incorrectly indented, which breaks compilation.

2022-11-24 16:49 UTC, fleischie commented on source/configuration_manual/authentication/authentication_mechanisms.rst
> +|                                                                              | :ref:`Winbind <authentication-winbind>`.                                 |                          |
This reference doesn't seem to exist in this branch.

2022-11-30 08:47 UTC, fleischie approved these changes

2022-11-30 08:59 UTC, merged