configuration_manual/authentication: Document event_ extra field
dovecot/documentation pull request #664
Opened 2023-02-02 11:08 UTC by cmouse

JIRA: DOV-5774

2023-02-02 11:08 UTC, cmouse commented
Cherrypick to 2.3

2023-02-03 15:14 UTC, sirainen requested changes

2023-02-03 15:14 UTC, sirainen commented on source/configuration_manual/authentication/user_database_extra_fields.rst
> +* ``event_<name>=value``: Import ``name=value`` to mail user event.
The first =value part is inconsistent both with how this list works and how it was in the passdb list, so just remove it.

2023-02-03 15:53 UTC, sirainen approved these changes

2023-02-08 10:57 UTC, merged