configuration_manual: Add note about extra fields accepting empty string values
dovecot/documentation pull request #668
Opened 2023-02-07 09:32 UTC by mbettini-ox

2023-02-07 17:49 UTC, sirainen requested changes

2023-02-07 17:49 UTC, sirainen commented on source/configuration_manual/authentication/user_database_extra_fields.rst
> +   Extra fields can now also be set to empty string;
..to empty string, while previously they were changed to "yes".

2023-02-07 17:49 UTC, sirainen commented on source/configuration_manual/authentication/user_database_extra_fields.rst
> +   extra fields without value will default to empty string as well.
Is this true? I thought the code still uses "yes" for these on the auth process side? Also it's not very clear what "without value" means, maybe "without '='"

2023-02-07 17:49 UTC, sirainen commented on source/configuration_manual/authentication/user_database_extra_fields.rst
> +.. versionchanged:: v3.0.0;v2.4.0
Should also write the same for passdb page.

2023-02-08 10:56 UTC, cmouse commented on source/configuration_manual/authentication/user_database_extra_fields.rst
> +   `yes`.
you need to use 

```
``yes``
```

2023-02-08 11:08 UTC, cmouse approved these changes

2023-02-08 11:10 UTC, merged