Config rewrite changes
dovecot/documentation pull request #789
Opened 2023-10-12 21:32 UTC by sirainen

2023-11-06 08:01 UTC, cmouse requested changes

2023-11-06 08:23 UTC, sirainen commented on source/configuration_manual/mail_location/obox/dictmap.rst
> +	 fs_parent {
Maybe, but we should discuss it further before doing a huge rename. Also there is the issue that the current way is hierarchical:

```
fs_parent {
  fs_parent {
     fs_parent {
```

Whereas somehow I'd expect fs_next to work like:

```
fs_next {
}
fs_next {
}
fs_next {
}
```

But that way of using fs_next would require naming each section for it to work, which is a bit unnecessary.

2023-11-06 08:27 UTC, cmouse commented on source/configuration_manual/mail_location/obox/dictmap.rst
> +	 fs_parent {
I guess I could live with fs_child too. I know from Code Point Of View it makes sense, but from Config Point Of View, it is a child.

2023-11-09 09:07 UTC, sirainen commented on source/configuration_manual/mail_compress_plugin.rst
> +  # Enable this only if you want compression while saving:
This is trying to say a different thing, but seems rather unnecessary. If you enable mail_compress plugin you almost certainly want to compress the mails. So I'll change it to `# Enable compressing the mails while saving (not just reading):`

2023-11-10 08:42 UTC, merged