config_variables: Document system: key
dovecot/documentation pull request #807
Opened 2023-11-22 10:11 UTC by cmouse

JIRA: DOV-6325

2023-11-30 19:54 UTC, sirainen requested changes

2023-11-30 19:54 UTC, sirainen commented on source/configuration_manual/config_file/config_variables.rst
> +  :ref:`mail user variables <variables-mail_user>`.
I don't think system:hostname is overridden? It could maybe point to the %{hostname} in there, and vice versa.

2023-11-30 19:54 UTC, sirainen commented on source/configuration_manual/config_file/config_variables.rst
> +  :ref:`mail service user variables <variables-mail_service_user>`
Same in these

2023-11-30 19:54 UTC, sirainen commented on source/configuration_manual/config_file/config_variables.rst
> -+------------+-----------------------------------------------------------------------------+
Commit message could also mention process: key

2024-01-08 12:27 UTC, cmouse commented
nits addressed.

2024-01-08 13:44 UTC, sirainen requested changes

2024-01-08 13:44 UTC, sirainen commented on source/configuration_manual/config_file/config_variables.rst
> +  environment variable.
\`\`DOVECOT_HOSTNAME\`\` and could also mention it's needed to be set in :ref:import_environment setting.

2024-01-16 20:30 UTC, sirainen requested changes

2024-01-16 20:30 UTC, sirainen commented on source/configuration_manual/config_file/config_variables.rst
> +  Number of CPUs available. Works only on Linux and FreeBSD-like systems.
Mention also NCPU environment & import_environment.

2024-01-16 21:53 UTC, sirainen approved these changes

2024-01-16 22:02 UTC, sirainen requested changes

2024-01-29 11:38 UTC, sirainen approved these changes

2024-01-31 13:01 UTC, merged