Languages config-rewrite
dovecot/documentation pull request #846
Opened 2024-02-13 17:20 UTC by mbettini-ox

2024-02-13 22:50 UTC, sirainen requested changes

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +     looked up in ``”<path>”/stopwords_<lang>.txt``.
the quotes around `<path>` seem unnecessary. Although maybe the whole `<path>` is unnecessary and it should just be:

```
     Path to the directory containing stopword files. The files are named `stopwords_<lang>.txt`.
```

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +     ``language_tokenizer_generic_algorithm = tr29 language_tokenizer_generic_wb5a = yes``.
I think this needs something like:

```
     ``language_tokenizer_generic_algorithm = tr29`` and ``language_tokenizer_generic_wb5a = yes``.
```

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   ``language_tokenizer_generic_algorithm = tr29 language_tokenizer_generic_wb5a = yes``.
similarly here "and" in the middle

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   :default: see note below
Use `!<filter/tokenizer-specific>` which is similar as used elsewhere.

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   :values: @named_filter
named_list_filter

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   recognition fails.
Hmm. This is actually a bit bad. The order of named list filters isn't very clear in all situations, and I was hoping to eventually not give any guarantees about that. Maybe we need to have language_default=yes|no setting, similar to the namespace_inbox=yes|no setting that namespaces have.

2024-02-13 22:50 UTC, sirainen commented on source/configuration_manual/fts/tokenization.rst
> +Stemming support indicates whether the ``snowball`` filter can be used.
Could this link to snowball instead?

2024-02-13 22:50 UTC, sirainen commented on source/installation_guide/upgrading/from-2.3-to-3.0.rst
> +| ``fts_languages``                                          | Converted into Renamed to :dovecot_core:ref:`language` blocks {}                         |
extra words: "Converted into Renamed to"

2024-02-13 22:50 UTC, sirainen commented on source/installation_guide/upgrading/from-2.3-to-3.0.rst
> +| ``fts_tokenizers``                                         | Split into :dovecot_core:ref:`language_tokenizer_generic_algorithm`                      |
Is there no generic language_tokenizers link that can be given, like above you link to language_filters?

2024-02-13 22:50 UTC, sirainen commented on source/configuration_manual/fts/dovecot.rst
> +  #  stems the words and lastly removes stopwords.
extra space after `#`

2024-02-13 22:50 UTC, sirainen commented on source/configuration_manual/fts/dovecot.rst
> +  # English and French.
These English and French could be comments below, e.g. `language en { # English`

2024-02-13 22:50 UTC, sirainen commented on source/configuration_manual/fts/tokenization.rst
> +List of tokenizers to use. Tokenizers can be language specific
missing period

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   (e.g. ``language_filters_en``).
This is now wrong/obsolete

2024-02-13 22:50 UTC, sirainen commented on source/settings/core.rst
> +   ``language_tokenizers_<lang>`` (e.g. ``language_tokenizers_en``).
This is now wrong/obsolete

2024-02-14 17:18 UTC, sirainen requested changes

2024-02-14 17:18 UTC, sirainen commented on source/configuration_manual/fts/dovecot.rst
> +    language_filters = lowercase snowball english-possessive stopwords
Can be just `filters` here. I've generally removed the unnecessary prefix in example configs.

2024-02-14 17:18 UTC, sirainen commented on source/configuration_manual/fts/tokenization.rst
> +    language_tokenizers = generic
just `tokenizers`

2024-02-14 17:18 UTC, sirainen commented on source/configuration_manual/fts/tokenization.rst
> +    language_filters = normalizer-icu snowball english-possessive stopwords
just `filters`

2024-02-14 17:18 UTC, sirainen commented on source/settings/core.rst
> +       language_filters = lowercase snowball english-possessive stopwords
just `filters`

2024-02-14 17:18 UTC, sirainen commented on source/settings/core.rst
> +      language_tokenizers = generic
just `tokenizers`

2024-02-14 17:18 UTC, sirainen commented on source/configuration_manual/fts/dovecot.rst
> +  language en { # English - 1st language is also the default for detection.
Needs updating for the language_default setting

2024-02-28 10:36 UTC, mbettini-ox commented on source/settings/core.rst
> +.. dovecot_core:setting:: language_token_maxlen
no longer there

2024-02-29 10:45 UTC, sirainen requested changes

2024-02-29 10:45 UTC, sirainen commented on source/settings/core.rst
> +       * :dovecot_core:ref:`language_filter_lowercase_token_maxlen`
no language_filter_lowercase_token_maxlen anymore

2024-03-11 13:09 UTC, merged