man: Document -c option for doveadm
dovecot/documentation pull request #871
Opened 2024-04-05 06:25 UTC by cmouse

2024-04-05 12:36 UTC, sirainen submitted a review, later dismissed

2024-04-09 10:01 UTC, fleischie requested changes

2024-04-09 10:01 UTC, fleischie commented on source/man/global-options.inc.in
> +
Would it be possible to match the order of the options here with the SYNOPSIS?

So `[-DOkv]` but then `-c`, `-f`, `-i`, and only then `-o`. I was a bit confused that I didn't find the option where I was looking for it. Feel free to disagree and resolve this comment unchanged. :)

2024-04-09 11:16 UTC, cmouse commented on source/man/doveadm-acl.1.rst.in
> +**doveadm** [*global options*] **acl** *command* [*OPTIONS*] [*ARGUMENTS*]
i suppose.

2024-04-09 11:17 UTC, cmouse commented on source/man/global-options-formatter.inc.in
> +.. include:: global-options.inc
um, no? why would it?

2024-04-09 11:18 UTC, cmouse commented on source/man/global-options-formatter.inc.in
> +.. include:: global-options.inc
in this commit, global-options-formatter.inc will have same options as it had before, nothing changes. the next commit adds new options.

2024-04-09 11:46 UTC, fleischie commented on source/man/global-options-formatter.inc.in
> +.. include:: global-options.inc
Ah ok. Excuse my fallacy, I must not have been thinking straight. :open_mouth:

2024-04-09 11:48 UTC, fleischie approved these changes

2024-04-09 12:08 UTC, merged