list_of_events: Document new fields in user and user group moves
dovecot/documentation pull request #886
Opened 2024-05-31 10:43 UTC by cmouse

JIRA: DOV-6714

2024-05-31 21:07 UTC, sirainen approved these changes

2024-06-03 10:07 UTC, sirainen requested changes

2024-06-03 10:07 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +   :field src_backend_host: Hostname of the source backend.
source_* here and below

2024-06-03 10:07 UTC, sirainen commented on source/admin_manual/list_of_events.rst
> +   :field src_backend_host: Hostname of the source backend.
missing site fields

2024-08-30 19:26 UTC, slusarz commented
This needs to be in Pro docs.

2024-08-30 19:26 UTC, closed without merging