Add quota_mailbox_message_count setting
dovecot/documentation pull request #936
Opened 2024-07-11 08:03 UTC by sirainen

DOV-6809

2024-07-11 14:00 UTC, fleischie requested changes
Needs local rebase. Changes themselves are ok!

2024-07-11 16:16 UTC, sirainen commented
> Needs local rebase.

How do you see that? It should be against the current main already, so doesn't even need a rebase..

2024-07-12 06:15 UTC, fleischie commented
Sorry, I was looking at the wrong repo. :bow:

2024-07-12 06:18 UTC, fleischie approved these changes

2024-07-12 14:49 UTC, merged